export default {
  //SYS ACTIONS
  ERROR_OCCURED: "ERROR_OCCURED",
  ERROR_CLEAR: "ERROR_CLEAR",

  //AUTH ACTIONS
  USER_SIGNIN_ATTEMPT: "USER_SIGNIN_ATTEMPT",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_ERROR: "USER_SIGNIN_ERROR",

  USER_SIGNOUT: "USER_SIGNOUT",

  // LISTING ACTIONS
  ARTIST_SEARCH_ATTEMPT: "ARTIST_SEARCH_ATTEMPT",
  ARTIST_SEARCH_SUCCESS: "ARTIST_SEARCH_SUCCESS",
  ARTIST_SEARCH_ERROR: "ARTIST_SEARCH_ERROR",

  GET_ARTIST_ALBUMS_ATTEMPT: "GET_ARTIST_ALBUMS_ATTEMPT",
  GET_ARTIST_ALBUMS_SUCCESS: "GET_ARTIST_ALBUMS_SUCCESS",
  GET_ARTIST_ALBUMS_ERROR: "GET_ARTIST_ALBUMS_ERROR"
};
